[project]
name = "dlt-iceberg-slack-backup"
version = "0.1.0"
description = "POC to backup slack messages to iceberg"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dagster-webserver>=1.9.6",
    "dagster>=1.9.6",
    "dlt[duckdb,pyiceberg]>=0.5.1",
    "duckdb>=1.1.3",
    "slack-sdk>=3.34.0",
    "toml>=0.10.2",
    "sqlalchemy>=2.0.18",
    "pyiceberg[pyarrow,sql-sqlite]>=0.8.1",
]

[project.optional-dependencies]
dev = [
    "dagster-webserver", 
    "pytest",
]

[tool.dagster]
module_name = "slack_backup.definitions"
project_name = "slack_backup"

[tool.setuptools.packages.find]
exclude=["slack_backup_tests"]
