[project]
name = "sqlmesh-slack-backup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dlt[duckdb]>=0.5.1",
    "duckdb>=1.1.3",
    "slack-sdk>=3.34.0",
    "sqlmesh[dlt,duckdb]>=0.141.1",
    "toml>=0.10.2",
]
